module: 'PCloudSDKSwift'
module_version: 3.0.1

author: 'pCloud'
author_url: 'http://pcloud.com'
theme: 'apple'

readme: 'README.md'
github_url: 'https://github.com/pcloud/pcloud-sdk-swift'

source_directory: 'PCloudSDKSwift'
exclude: '**/*.h'
# swift_version: 3.0
clean: true
